/* soapServer.c
   Generated by gSOAP 2.8.87 for wssedemo.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.87 2019-08-26 14:37:56 GMT")
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	soap->keep_alive = soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
			soap->keep_alive--;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:add"))
		return soap_serve_ns1__add(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:sub"))
		return soap_serve_ns1__sub(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:mul"))
		return soap_serve_ns1__mul(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:div"))
		return soap_serve_ns1__div(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__add(struct soap *soap)
{	struct ns1__add soap_tmp_ns1__add;
	struct ns1__addResponse soap_tmp_ns1__addResponse;
	double soap_tmp_double;
	soap_default_ns1__addResponse(soap, &soap_tmp_ns1__addResponse);
	soap_default_double(soap, &soap_tmp_double);
	soap_tmp_ns1__addResponse.result = &soap_tmp_double;
	soap_default_ns1__add(soap, &soap_tmp_ns1__add);
	if (!soap_get_ns1__add(soap, &soap_tmp_ns1__add, "ns1:add", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__add(soap, soap_tmp_ns1__add.a, soap_tmp_ns1__add.b, soap_tmp_ns1__addResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns1__addResponse(soap, &soap_tmp_ns1__addResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__addResponse(soap, &soap_tmp_ns1__addResponse, "ns1:addResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__addResponse(soap, &soap_tmp_ns1__addResponse, "ns1:addResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__sub(struct soap *soap)
{	struct ns1__sub soap_tmp_ns1__sub;
	struct ns1__subResponse soap_tmp_ns1__subResponse;
	double soap_tmp_double;
	soap_default_ns1__subResponse(soap, &soap_tmp_ns1__subResponse);
	soap_default_double(soap, &soap_tmp_double);
	soap_tmp_ns1__subResponse.result = &soap_tmp_double;
	soap_default_ns1__sub(soap, &soap_tmp_ns1__sub);
	if (!soap_get_ns1__sub(soap, &soap_tmp_ns1__sub, "ns1:sub", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__sub(soap, soap_tmp_ns1__sub.a, soap_tmp_ns1__sub.b, soap_tmp_ns1__subResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns1__subResponse(soap, &soap_tmp_ns1__subResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__subResponse(soap, &soap_tmp_ns1__subResponse, "ns1:subResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__subResponse(soap, &soap_tmp_ns1__subResponse, "ns1:subResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__mul(struct soap *soap)
{	struct ns1__mul soap_tmp_ns1__mul;
	struct ns1__mulResponse soap_tmp_ns1__mulResponse;
	double soap_tmp_double;
	soap_default_ns1__mulResponse(soap, &soap_tmp_ns1__mulResponse);
	soap_default_double(soap, &soap_tmp_double);
	soap_tmp_ns1__mulResponse.result = &soap_tmp_double;
	soap_default_ns1__mul(soap, &soap_tmp_ns1__mul);
	if (!soap_get_ns1__mul(soap, &soap_tmp_ns1__mul, "ns1:mul", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__mul(soap, soap_tmp_ns1__mul.a, soap_tmp_ns1__mul.b, soap_tmp_ns1__mulResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns1__mulResponse(soap, &soap_tmp_ns1__mulResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__mulResponse(soap, &soap_tmp_ns1__mulResponse, "ns1:mulResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__mulResponse(soap, &soap_tmp_ns1__mulResponse, "ns1:mulResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__div(struct soap *soap)
{	struct ns1__div soap_tmp_ns1__div;
	struct ns1__divResponse soap_tmp_ns1__divResponse;
	double soap_tmp_double;
	soap_default_ns1__divResponse(soap, &soap_tmp_ns1__divResponse);
	soap_default_double(soap, &soap_tmp_double);
	soap_tmp_ns1__divResponse.result = &soap_tmp_double;
	soap_default_ns1__div(soap, &soap_tmp_ns1__div);
	if (!soap_get_ns1__div(soap, &soap_tmp_ns1__div, "ns1:div", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns1__div(soap, soap_tmp_ns1__div.a, soap_tmp_ns1__div.b, soap_tmp_ns1__divResponse.result);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"; /* use SOAP encoding style */
	soap_serializeheader(soap);
	soap_serialize_ns1__divResponse(soap, &soap_tmp_ns1__divResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__divResponse(soap, &soap_tmp_ns1__divResponse, "ns1:divResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__divResponse(soap, &soap_tmp_ns1__divResponse, "ns1:divResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
